In [1]:
import numpy as np

result_array = np.array([])

array1 = np.arange(24).reshape([2,3,4])
print('arr1\n',array1)
array2 = np.arange(24,48).reshape([2,3,4])
print('arr2\n',array2)

result_array = np.vstack((array1[np.newaxis, :], array2[np.newaxis, :]))

print(result_array.shape)

arr1
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
arr2
 [[[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
(2, 2, 3, 4)


In [17]:
import numpy as np

# Create an empty array
result_array = np.array([])

# Example arrays to append
for i in range(3):
    array1 = np.arange(24).reshape([2,3,4])[np.newaxis,:]
    if result_array.size == 0:
        result_array = array1
    else:
        result_array = np.append(result_array, array1, axis=0)


print(result_array.shape)
print(result_array)


(3, 2, 3, 4)
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]


In [12]:
import numpy as np

# Create an empty array
result_array = np.array([])

# Example arrays to append
for i in range(3):
    new_array = np.array([i, i + 1, i + 2])
    
    # Check if the result_array is empty
    if result_array.size == 0:
        result_array = new_array
    else:
        # Append along the first axis (axis=0)
        result_array = np.append(result_array, new_array, axis=1)

print(result_array)

AxisError: axis 1 is out of bounds for array of dimension 1

In [21]:
import numpy as np
import timeit

# Example arrays to append or concatenate
num_arrays = 10000
array_size = 3

arrays_to_append = [np.array([i, i + 1, i + 2]) for i in range(num_arrays)]

# Using np.append in a loop
def append_in_loop():
    result_array = np.array([])
    for arr in arrays_to_append:
        result_array = np.append(result_array, arr)
    return result_array.reshape((-1, array_size))

# Using np.vstack
def vstack_directly():
    return np.vstack(arrays_to_append)

# Measure execution time
time_append = timeit.timeit(append_in_loop, number=1000)
time_vstack = timeit.timeit(vstack_directly, number=1000)

print(f"Time for np.append in a loop: {time_append:.6f} seconds")
print(f"Time for np.vstack: {time_vstack:.6f} seconds")

Time for np.append in a loop: 43.938956 seconds
