In [3]:
import torch
import numpy as np


path = '/home/koki/mlp_glue/data/megadepth_scene_info/'
index = '0000'
data = np.load(path + index +'.npz', allow_pickle = True)

keys = data.files
print(keys)


['image_paths', 'depth_paths', 'intrinsics', 'poses', 'overlap_matrix', 'scale_ratio_matrix', 'angles', 'n_points3D', 'points3D_id_to_2D', 'points3D_id_to_ndepth']


In [53]:
type(data['image_paths'][1])

str

In [50]:
length = len(data['image_paths'])
for i in range(length):
    data['image_paths'][i] = f'/home/koki/mlp_glue/data/megadepth_train/0000/dense0/imgs/{i}.jpg'
    print(data['image_paths'][i])
print()
print(len(data['image_paths']))

None
Undistorted_SfM/0000/images/3409963756_f34ab1229a_o.jpg
None
Undistorted_SfM/0000/images/3409058203_7a62e17d8f_o.jpg
Undistorted_SfM/0000/images/3409057929_f5053f6dcd_o.jpg
None
Undistorted_SfM/0000/images/3400313166_a927738c48_o.jpg
Undistorted_SfM/0000/images/3392691648_0071a50c06_o.jpg
None
Undistorted_SfM/0000/images/3391896829_8e44012068_o.jpg
None
None
Undistorted_SfM/0000/images/2094364564_41251e11d5_o.jpg
None
Undistorted_SfM/0000/images/3391383354_4106b62611_o.jpg
Undistorted_SfM/0000/images/3391357880_11f43a9bef_o.jpg
Undistorted_SfM/0000/images/2093587649_23bf61292f_o.jpg
None
None
None
None
Undistorted_SfM/0000/images/3387723870_03c2e97040_o.jpg
Undistorted_SfM/0000/images/3387722702_46367ae130_o.jpg
None
None
None
None
Undistorted_SfM/0000/images/2074796674_75385e5120_o.jpg
None
None
Undistorted_SfM/0000/images/2074795864_612b242ce3_o.jpg
Undistorted_SfM/0000/images/3383895231_cee5172a72_o.jpg
Undistorted_SfM/0000/images/1359386379_08f0b76a41_o.jpg
None
Undistorted_Sf

In [14]:
for i in range(5):
    print(data['depth_paths'][i])
print()
print(len(data['depth_paths']))

None
phoenix/S6/zl548/MegaDepth_v1/0000/dense0/depths/3409963756_f34ab1229a_o.h5
None
phoenix/S6/zl548/MegaDepth_v1/0000/dense0/depths/3409058203_7a62e17d8f_o.h5
phoenix/S6/zl548/MegaDepth_v1/0000/dense0/depths/3409057929_f5053f6dcd_o.h5

3803


In [15]:
for i in range(5):
    print(data['intrinsics'][i])
print()
print(len(data['intrinsics']))

None
[[1.90095e+03 0.00000e+00 6.40000e+02]
 [0.00000e+00 1.90135e+03 4.80000e+02]
 [0.00000e+00 0.00000e+00 1.00000e+00]]
None
[[1.20923e+03 0.00000e+00 5.20000e+02]
 [0.00000e+00 1.20923e+03 3.87000e+02]
 [0.00000e+00 0.00000e+00 1.00000e+00]]
[[1.20469e+03 0.00000e+00 5.23000e+02]
 [0.00000e+00 1.20469e+03 3.88000e+02]
 [0.00000e+00 0.00000e+00 1.00000e+00]]

3803


In [16]:
for i in range(5):
    print(data['poses'][i])
print()
print(len(data['poses']))

None
[[ 0.9978149  -0.00506082  0.06587729 -0.749445  ]
 [ 0.01442063  0.9897053  -0.14239197 -3.9046    ]
 [-0.06447848  0.14303082  0.98761567 -1.52595   ]
 [ 0.          0.          0.          1.        ]]
None
[[-0.999683   -0.00814959 -0.0238219  -0.279396  ]
 [-0.01353577  0.97176003  0.23558273 -3.73789   ]
 [ 0.02122927  0.2358305  -0.9715623  -1.77511   ]
 [ 0.          0.          0.          1.        ]]
[[-0.14726894 -0.01778784  0.98893653  0.22014   ]
 [ 0.14065731  0.9893001   0.03874057 -3.88186   ]
 [-0.97904412  0.14480643 -0.14319119 -1.29168   ]
 [ 0.          0.          0.          1.        ]]

3803


In [ ]:
import time
start = time.time()
length = len(data['overlap_matrix'])
for i in range(length):
    print(data['overlap_matrix'][0][i])
end = time.time()

print(end-start)
# print(data['overlap_matrix'][0][17])
# print(data['overlap_matrix'].shape)

In [35]:
greater_than_zero_mask = data['overlap_matrix'][1] > 0
print(data['overlap_matrix'][1][greater_than_zero_mask])

[0.24305556 0.00138889 0.08888889 0.09583333 0.02916667 0.19583333
 0.10972222 0.07222222 0.03055556 0.02638889 0.23055556 0.00277778
 0.03611111 0.07777778 0.00277778 0.04027778 0.00833333 0.01805556
 0.08333333 0.00416667 0.00972222 0.01666667 0.00694444 0.01527778
 0.04027778 0.00833333 0.12916667 0.0625     0.01111111 0.10277778
 0.03472222 0.00416667 0.02777778 0.14027778 0.15972222 0.04583333
 0.01944444 0.01111111 0.00416667 0.05277778 0.1875     0.02361111
 0.12083333 0.04305556 0.01805556 0.04027778 0.05555556 0.01944444
 0.00694444 0.03611111 0.00555556 0.2125     0.00972222 0.30138889
 0.08888889 0.04722222 0.01944444 0.03333333 0.03333333 0.05
 0.04166667 0.11388889 0.00555556 0.1875     0.26527778 0.02083333
 0.00416667 0.03888889 0.04166667 0.00555556 0.00833333 0.00972222
 0.02222222 0.10972222 0.05       0.18888889 0.04861111 0.03333333
 0.03055556 0.01388889 0.025      0.02777778 0.16111111 0.0125
 0.01111111 0.00972222 0.00972222 0.00694444 0.29583333 0.00277778
 0.00

In [34]:
print(len(data['overlap_matrix'][1]))

3803


In [48]:
index = 90
indices = np.where(data['overlap_matrix'][index] > 0)

print(len(indices[0]))
print(indices[0])
print(data['overlap_matrix'][index][indices])


302
[  15   31   63   94   98  104  110  144  148  153  156  157  175  188
  191  199  209  210  214  217  239  248  252  265  305  307  317  323
  335  339  341  356  413  418  422  424  439  465  468  470  498  517
  523  538  545  555  574  581  591  597  613  614  620  621  623  657
  687  724  726  743  772  794  816  820  839  846  854  870  878  883
  890  910  929  940  955  956  975  977  985  996 1003 1007 1012 1052
 1055 1059 1069 1076 1083 1096 1136 1137 1148 1156 1157 1182 1185 1194
 1205 1208 1231 1247 1249 1256 1287 1299 1307 1314 1335 1341 1344 1345
 1370 1389 1394 1396 1399 1426 1434 1440 1445 1537 1551 1563 1587 1591
 1624 1641 1659 1668 1700 1708 1717 1721 1747 1751 1800 1804 1805 1819
 1822 1835 1843 1897 1915 1944 1993 2033 2038 2051 2062 2065 2068 2073
 2080 2090 2107 2114 2120 2122 2124 2131 2141 2162 2190 2198 2212 2218
 2219 2221 2225 2250 2253 2280 2291 2320 2336 2363 2367 2376 2381 2387
 2398 2401 2406 2408 2409 2417 2430 2443 2452 2458 2459 2481 2498 2510
 2

In [55]:
from pathlib import Path

url_base = "http://ptak.felk.cvut.cz/revisitop/revisitop1m/"
list_name = "revisitop1m.txt"
tmp_dir = Path('/home/koki/mlp_glue')
torch.hub.download_url_to_file(url_base + list_name, tmp_dir / list_name)

100%|██████████| 38.2M/38.2M [00:05<00:00, 7.01MB/s]


In [ ]:
file_prefix = '000'
file_extension = '.npz'

# Specify the range of file numbers (assuming you want to go up to 5018)
start_number = 0
end_number = 5018

# Create the list of file names
file_names = [f'{i:04d}' for i in range(start_number, end_number + 1)]

# Print the list of file names
print(file_names[-10:])

In [ ]:
import numpy as np
import os


file_path_with_tilde = '~/mlp_glue/data/megadepth_scene_info/0000.npz'
expanded_file_path = os.path.expanduser(file_path_with_tilde)
x = np.load(expanded_file_path,allow_pickle=True)
print(x['image_paths'][1])



cnt = 0
import os
# /home/koki/mlp_glue/data/megadepth_scene_info
file_extension = '.npz'
data_path = '/home/koki/mlp_glue/data/megadepth_scene_info/'

for name in file_names:
    file = data_path + name + file_extension
    if os.path.isfile(file):
        cnt+=1
        with open('megadepth_full.txt','a') as file:
            file.write(name + '\n')
    
print(cnt)

In [ ]:
cnt = 0
import os
# /home/koki/mlp_glue/data/megadepth_scene_info
file_extension = '.npz'
data_path = '/home/koki/mlp_glue/data/megadepth_scene_info/'

lit = []
for name in file_names:
    file = data_path + name + file_extension
    if os.path.isfile(file):
        lit.append(name+'.npz')
print(lit)

In [ ]:
cnt = 0
for name in lit:
    x = np.load(data_path+name,allow_pickle=True)
    x = x['depth_paths']
    y = x[x != None]
    cnt += len(y)
    print(name,len(y))
print(cnt)